# Alacritty config

# ---------- general ----------
[general]
# auto reloading
live_config_reload = true
# colorscheme
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

# ---------- fonts ----------
[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

# ---------- pretty dress ----------
[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
decorations = "None"
# Windowed, Maximized, Fullscreen
startup_mode = "Maximized"

[window.dimensions]
columns = 70
lines = 20

[mouse]
hide_when_typing = true

# ---------- key bindings ----------
[keyboard]
bindings = [
  { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "T", mods = "Command", action = "SpawnNewInstance" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "V", mods = "Command", action = "Paste" },
]
