# aliases
alias ls="ls -G"
alias zshconfig="mate ~/.zshrc"
alias vi="nvim"
alias vim="nvim"
alias ra="ranger"
alias lg="lazygit"
alias nf="neofetch"
alias icat="kitty +kitten icat"
alias chrome="google-chrome"
alias pigcha="PigchaProxy"
