# =============================================================
#
# ██╗    ███╗██╗   ██╗███████╗███████╗██╗  ██╗██████╗  ██████╗
# ████╗ ████║╚██╗ ██╔╝╚══███╔╝██╔════╝██║  ██║██╔══██╗██╔════╝
# ██╔████╔██║ ╚████╔╝   ███╔╝ ███████╗███████║██████╔╝██║     
# ██║╚██╔╝██║  ╚██╔╝   ███╔╝  ╚════██║██╔══██║██╔══██╗██║     
# ██║ ╚═╝ ██║   ██║   ███████╗███████║██║  ██║██║  ██║╚██████╗
# ╚═╝     ╚═╝   ╚═╝   ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝
#
# =============================================================

# Author: @hnpyn

# =========================== Basic ===========================
# My zsh path
ZSH="$HOME/.zsh"

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=2000
SAVEHIST=1000

# =========================== OS ==============================
case "$(uname -s)" in
  Darwin )
    source "$ZSH/os/macos.zsh"
    ;;
  Linux )
    source "$ZSH/os/linux.zsh"
    ;;
esac

# ========================== Aliases ==========================
source "$ZSH/aliases.zsh"

# ========================== Plugins ==========================
PLUGINS="$ZSH/plugins"

autoload -Uz compinit && compinit

source "$PLUGINS/fzf-tab/fzf-tab.plugin.zsh"
source "$ZSH/fzf/fzf-tab.zsh"

source "$PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=96'

source "$PLUGINS/zsh-vi-mode/zsh-vi-mode.plugin.zsh"

eval "$(zoxide init zsh)"

eval "$(fnm env --use-on-cd --shell zsh)"

if [[ "${widgets[zle-keymap-select]#user:}" == "starship_zle-keymap-select" || \
      "${widgets[zle-keymap-select]#user:}" == "starship_zle-keymap-select-wrapped" ]]; then
    zle -N zle-keymap-select "";
fi
eval "$(starship init zsh)"

source "$PLUGINS/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"

# ========================== Env var ==========================
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH"

export all_proxy='socks5://127.0.0.1:7897'
export http_proxy='http://127.0.0.1:7897'
export https_proxy='http://127.0.0.1:7897'

# ========================== MISC =============================
# Preferred editor for local and remote sessions
if [[ -n "$SSH_CONNECTION" ]]; then
  export TERM='xterm-256color'
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Paste highlight
zle_highlight=('paste:none')
