#!/usr/bin/env sh

# Uses SF Symbols and https://www.nerdfonts.com/cheat-sheet

# General Icons
ICON_APPLE=􀣺
ICON_LOCK=􀒳
ICON_MUSIC=􀑪
ICON_BELL=􀋚
ICON_BELL_DOT=􀝗
ICON_LOADING=􀖇
ICON_ACTIVITY=􀒓
ICON_PREFERENCES=􀺽
ICON_DARK_MODE_ON=􀆺
ICON_DARK_MODE_OFF=􀆹
ICON_FORWARD=􂨬
ICON_BACKWARD=􂨫

# Network Icons
ICON_WIFI=􀙇
ICON_VPN=􀵴 # 􀞚 󰄛 􀆪 􁅍 􀵲
ICON_HOTSPOT=􀉤
ICON_SSID=􀤆
ICON_SPEED=􀍾

# Battery Icons
ICON_BATTERY_100=􀛨
ICON_BATTERY_75=􀺸
ICON_BATTERY_50=􀺶
ICON_BATTERY_25=􀛩
ICON_BATTERY_0=􀛪
ICON_BATTERY_CHARGING=􀢋

# Volume Icons
ICON_VOLUME_100=􀊩
ICON_VOLUME_66=􀊧
ICON_VOLUME_33=􀊥
ICON_VOLUME_10=􀊡
ICON_VOLUME_0=􀊣
ICON_AIRPODSPRO=􀪷
ICON_HEADPHONES=􀑈

# Yabai Icons
ICON_YABAI_STACK=􀏭
ICON_YABAI_FULLSCREEN_ZOOM=􀂓
ICON_YABAI_PARENT_ZOOM=􀥃
ICON_YABAI_FLOAT=􀢌
ICON_YABAI_GRID=􀧍
ICON_YABAI_SPLIT_VERTICAL=􀘜
ICON_YABAI_SPLIT_HORIZONTAL=􀧋

# My apps
ICON_DISCORD=      # Discord
ICON_TERM=         # fallback terminal app, terminal, warp, iterm2
ICON_PHOTOSHOP=    #
ICON_AFTEREFFECTS=󱁑 #
ICON_INDESIGN=󰴑     #
ICON_ILLUSTRATOR=  #
ICON_PHOTOS=       #
ICON_FIGMA=        #
ICON_KICAD=        #
ICON_REMINDERS=    #
ICON_DOWNLOAD=􁾮     # Jdownloader2
ICON_ICON=􀼱         # SF Symbols
ICON_STEAM=󰓓        # Steam
ICON_HANDBRAKE=󱁆
ICON_FIREFOX=󰈹
ICON_FONTBOOK=
ICON_GLM=󰓃
ICON_POPCORN=􁐈
ICON_DAISYDISK=󰞯
ICON_BRAIN=
ICON_STRESS=󰠠
